import Head from 'next/head'
import Link from 'next/link'
import client from '@/lib/apollo-client'
import { gql } from '@apollo/client'

export default function announcements({ announcements }) {
  return (
    <>
      <Head>
        <title>Hyper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Announcements:</h1>
      <Link href="/">main</Link>

      <div className="container">
        {announcements.map((ann, i) => (
          <>
            <h2 key={i}>{ann.title}</h2>
            <video
              src={ann.video.url}
              type="video/mp4"
              width="320"
              height="240"
              controls
            ></video>
          </>
        ))}
      </div>
    </>
  )
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query {
        announcements {
          title
          video {
            url
          }
        }
      }
    `,
  })
  const { announcements } = data
  return {
    props: {
      announcements,
    },
  }
}
